name: gufe
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - coverage
  - networkx
  - numpy
  - openff-toolkit >=0.13.0
  - openff-units <0.2.1  # https://github.com/openforcefield/openff-units/issues/69
  - pint <0.22  # https://github.com/openforcefield/openff-units/issues/69
  - openff-models >=0.0.5,<0.1.0
  - pip
  - pydantic <2.0.0
  - pytest
  - pytest-cov
  - pytest-xdist
  - typing-extensions
  - ambertools >=22.0  # why were we getting old ones?
  # docs
  - pydata-sphinx-theme
  - sphinx-jsonschema==1.15
  - pip:
    - autodoc_pydantic
