name: "conda_cron"
on:
  pull_request:
    branches:
      - main
  schedule:
    # At 07:00 UTC every day
    - cron: "0 7 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  condacheck:
    runs-on: ${{ matrix.OS }}-latest
    name: "daily conda check"
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'macos']
        python-version:
          - "3.9"
          - "3.10"

    steps:
      - name: setup-micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: False
          environment-name: gufe
          channels: conda-forge
          extra-specs: |
            python==${{ matrix.python-version }}

      - name: install-and-deps
        run: |
          micromamba install gufe pytest pytest-xdist pip -c conda-forge
          python -m pip install PyGithub

      - name: run-tests
        continue-on-error: true
        run: pytest -n auto --pyargs gufe

      - name: raise-or-close-issue
        env:
          CI_OUTCOME: ${{ steps.run-tests.outcome }}
          TITLE: "[CI] CONDA CRON FAILURE"
        shell: python {0}
        run: |
          import os
          import numpy as np
          from github import Github

          git = Github(os.environ['GITHUB_TOKEN'])
          status = os.environ['CI_OUTCOME']
          repo = git.get_repo('OpenFreeEnergy/gufe')
          title = os.environ['TITLE']

          target_issue = None
          for issue in repo.get_issues():
              if issue.title == title:
                  target_issue = issue
          
          # Close any issues with given title if CI returned green
          if status == 'passed':
              target_issue.edit(state='closed')
          else:
              # Otherwise raise an issue
              if target_issue is None:
                  repo.create_issue(title=title, body="")
